/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'accent-gold': '#FFC933',
        'accent-gold-light': '#FFF6DC',
        'accent-teal': '#102C4D',
        'accent-teal-light': '#E8EDF3',
        'ink-dark': '#0E2640',
        'ink-mid': '#1A3A5C',
        background: '#F7FAF9',
        'surface-warm': '#FFFFFF',
        'surface-fresh': '#EEF6F3',
        'surface-neutral': '#DDE3EA',
        'surface-container-low': '#F1F5F4',
        'surface-muted': '#E8EEEC',
        'border-subtle': '#DCE5E2',
        'text-muted': '#5F6F78',
        'on-surface': '#1A2B36',
        'primary-container': '#0E2640',
        error: '#E05252',
        'on-primary': '#ffffff',
        'on-background': '#1A2B36',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.25rem',
        full: '9999px',
      },
      boxShadow: {
        soft: '0 4px 24px -4px rgba(14, 38, 64, 0.08)',
        card: '0 8px 32px -8px rgba(14, 38, 64, 0.12)',
        gold: '0 8px 24px -6px rgba(255, 201, 51, 0.4)',
      },
      spacing: {
        'container-max-width': '1280px',
        'section-padding-mobile': '64px',
        baseline: '8px',
        'section-padding-desktop': '120px',
        'grid-gutter': '32px',
      },
      fontFamily: {
        'body-lg': ['Work Sans', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'label-sm': ['Work Sans', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        eyebrow: ['Work Sans', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'display-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'display-lg': ['72px', { lineHeight: '80px', letterSpacing: '-0.02em', fontWeight: '800' }],
        eyebrow: ['14px', { lineHeight: '20px', letterSpacing: '0.15em', fontWeight: '600' }],
        'headline-md': ['40px', { lineHeight: '48px', fontWeight: '700' }],
        'display-lg-mobile': ['48px', { lineHeight: '52px', letterSpacing: '-0.01em', fontWeight: '800' }],
      },
      maxWidth: {
        'container-max-width': '1280px',
      },
      keyframes: {
        navItemIn: {
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        certificateColumnScroll: {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-50%)' },
        },
      },
      animation: {
        navItemIn: 'navItemIn 0.38s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'certificate-scroll-15': 'certificateColumnScroll 15s linear infinite',
        'certificate-scroll-17': 'certificateColumnScroll 17s linear infinite',
        'certificate-scroll-19': 'certificateColumnScroll 19s linear infinite',
      },
      transitionTimingFunction: {
        'nav-panel': 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
    },
  },
  plugins: [],
};
